#spring.application.name=BeautyCenter
server:
  port: 8081
  servlet:
    context-path: /sbs
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sbs"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true