#spring.application.name=BeautyCenter
server:
  port: 8081
  servlet:
    context-path: /sbs
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sbs"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dungbnhe173185@fpt.edu.vn
    password: xcjxjvqsravhigzq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true