#spring.application.name=BeautyCenter
aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-1

server:
  port: 8081
  servlet:
    context-path: /sbs
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sbs"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.hibernate.dialect: MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: dungbnhe173185@fpt.edu.vn
    password: xcjxjvqsravhigzq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

